version: "3.8"

services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-on-3000
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: w2m-crdb-net
