version: '3.5'

services:

  crdb:
    image: cockroachdb/cockroach:v22.1.1
    container_name: w2m-cockroach01
    hostname: cockroach01
    environment:
      - MySampleVar=MySampleVal
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    command: start-single-node --insecure
    ports:
      - "8080:8080"
      - "26257:26257"

networks:
  default:
    external:
      name: w2m-crdb-net
