version: '3.5'

services:

  crdb:
    image: cockroachdb/cockroach:v22.1.1
    container_name: w2m-cockroach01f
    hostname: cockroach01f
    environment:
      - MySampleVar=MySampleVal
    volumes:
      - "${PWD}/fluentd-crdb-v2-log.yaml:/cockroach/fluentd-crdb-v2-log.yaml"
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    command: start-single-node --insecure --log-config-file=/cockroach/fluentd-crdb-v2-log.yaml
    ports:
      - "8080:8080"
      - "26257:26257"

networks:
  default:
    external:
      name: w2m-crdb-net
