version: '3.5'

volumes:
  certs_data: {}
  ca_data: {}

services:

  crdb:
    image: cockroachdb/cockroach:v22.1.1
    container_name: w2m-cockroach01c
    hostname: cockroach01c
    environment:
      - MySampleVar=MySampleVal
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
      - certs_data:/certs
      - ca_data:/ca
    command: start-single-node --certs-dir=./certs
    ports:
      - "8080:8080"
      - "26257:26257"

networks:
  default:
    external:
      name: w2m-crdb-net
